ecommerce/ecommerce/converstation/urls.py
from django.urls import path

from .import views

app_name = 'conversations'
urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

ecommerce/ecommerce/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name = 'core/login.html', authentication_form=LoginForm), name='login')
]

ecommerce/ecommerce/dashboard/urls.py
from django.urls import path

from .import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    ]

ecommerce/ecommerce/ecommerce/urls.py
from django.conf import settings # Dont do this in production
from django.conf.urls.static import static # dont do this in production
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include('core.urls')),
    path("items/", include('item.urls')),
    path("dashboard/", include('dashboard.urls')),
    path("inbox/", include('converstation.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # DO not do this in producion

ecommerce/ecommerce/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

ecommerce/ecommerce/core/models.py
from django.db import models

# Create your models here.

ecommerce/ecommerce/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 border border-gray-300 rounded-lg focus:outline-none focus:border-gray-400 focus:ring-0',
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 border border-gray-300 rounded-lg focus:outline-none focus:border-gray-400 focus:ring-0',
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 border border-gray-300 rounded-lg focus:outline-none focus:border-gray-400 focus:ring-0',
    }))

    email = forms.EmailField(widget=forms.TextInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 border border-gray-300 rounded-lg focus:outline-none focus:border-gray-400 focus:ring-0',
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 border border-gray-300 rounded-lg focus:outline-none focus:border-gray-400 focus:ring-0',
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm your password',
        'class': 'w-full py-4 px-6 border border-gray-300 rounded-lg focus:outline-none focus:border-gray-400 focus:ring-0',
    }))

ecommerce/ecommerce/core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item
from .forms import SignupForm

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

ecommerce/ecommerce/core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title %}{% endblock %} | Ecommerce</title>
    </head>
    <body> 
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-2xl font-bold">Ecommerce</a>
            <div class = "space-x-6">
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>
                <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
                {% if user.is_authenticated %}
                    <a href="{% url 'conversations:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                    {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
        </nav>
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>
        <footer class=" py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">This is a full stack porject I am making which is basically an ecommerce website and hopefully I finish this in a day so that I can use this project as a baseline to create another full stack porject which will hopefully incoorporate a machine learning concept in it and maybe make another website that just teaches machine learning concepts more efficiently as I cant seem to think of anything better to do and take up my time than making full stack projects eventhough I am a machine learnign engineer and I cant find a job in the Machine Learning market as the job market sucks and the compaines suck and no wants want to give chance to someone who has a graduate visa and the govenment does not help. I wanted to become a game developer you know and who knows, that might be one of the other projects I mihgt end up making in the future. Probably a horror game as that shows and reflects whats most of what life has been like. Now this rant will finally come to an end. Hope You enjoyed my menatl breakdown :)</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
                <ul class="spcae-y-2">
                    <li>
                        <a href="#" class="text-lg text-teal-700 hover:text-teal-500">About</a>
                    </li>
                    <li>
                        <a href="{% url 'core:contact' %}" class="text-lg text-teal-700 hover:text-teal-500">Contact</a>
                    </li>
                    <li>
                        <a href="#" class="text-lg text-teal-700 hover:text-teal-500">Privacy Policy</a>
                    </li>
                    <li>
                        <a href="#" class="text-lg text-teal-700 hover:text-teal-500">Term of use</a>
                    </li>
                </ul>
            </div>
        </footer>
    </body>

</html>

ecommerce/ecommerce/core/templates/core/contact.html
{% extends "core/base.html" %}

{%block title %}Contact{% endblock %}

{% block content %}
    <h1>The Contact Page</h1>
{% endblock %}

ecommerce/ecommerce/core/templates/core/index.html
{% extends "core/base.html" %}

{%block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest Items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">  <!--item:detail is the name space for the items detail -->
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-5 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <div>
                <a href="#">
                    <div class="p-5 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-500">{{ category.items.count }} items</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

ecommerce/ecommerce/core/templates/core/login.html
{% extends "core/base.html" %}

{%block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}
        
        
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        

        {% if form.errorts or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors}}
            </div>
        {% endif %}
        

        <button class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Submit</button>
    </form>
</div>
{% endblock %}

ecommerce/ecommerce/core/templates/core/signup.html
{% extends "core/base.html" %}

{%block title %}Sign Up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign Up</h1>

    <form method="post" action=".">
        {% csrf_token %}
        
        
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat Password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errorts or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors}}
            </div>
        {% endif %}
        

        <button class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Submit</button>
    </form>
</div>
{% endblock %}